dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
install:
  - pip install coveralls
before_script: cd ospa
script:
  coverage run -m unittest test_ospa.py
after_success:
  - coveralls